### ISSUE TITLE
Unable to save new pastes, existing ones won't load

### ISSUE THREAD

**Issue by Adubbz** [seejohnrun/haste-server#202] opened 2018-02-16 10:41 UTC
Hey there, my apologies if this is the incorrect place to put this however it seems I am unable to save or load any pastes on https://hastebin.com/. 

After entering some text and pressing the save button, nothing happens for ~30 seconds, before a red box appears saying "Something went wrong!". Additionally, upon loading any page (https://hastebin.com/about.md for example) the page is blank, and a cursor appears after ~20-30 seconds. This behaviour happens on Chrome, Edge and Internet Explorer on Windows, as well as Safari on both macOS and iOS. I have also confirmed this with others as well. 

I hope the service is back to functioning normally again soon, since it's one that I, and I'm sure many others, enjoy using regularly. Thanks.

**Comment by seejohnrun** [comment] 2018-02-16 14:56
This should be fixed now, thank you!

**Closed by seejohnrun** 2018-02-16 14:56 UTC

**Comment by TheMonDon** [comment] 2018-12-08 03:11
I'm having this issue now

**Comment by Hundeklemmen** [comment] 2018-12-11 18:08
same

**Comment by Gyzimo** [comment] 2019-01-23 02:41
Jup i have the same problem.  it will not save it

**Comment by Dimentive** [comment] 2019-03-09 01:48
I can’t save any Hastebeen pastes, no matter how long or short they are.

**Comment by Dimentive** [comment] 2019-03-09 01:49
@seejohnrun It hasn’t been fixed; I’m having this issue right now. I can’t save any Hastebeen pastes, no matter how long or short they are.

**Comment by SylveonBottle** [comment] 2019-03-22 00:26
Happening now.

**Comment by Gyzimo** [comment] 2019-03-22 01:17
Yeah I thought I just closed brackets and killed all tasks in tasks mananger. Other then that is that not works then reinstalling is I think the only option.

**Comment by Kabouik** [comment] 2019-03-29 14:02
Same here!

**Comment by weegeeweeg** [comment] 2019-04-13 17:01
> This should be fixed now, thank you!

**Comment by beyzakorkmaz391** [comment] 2019-04-21 12:14
It's not.

**Comment by 32** [comment] 2019-05-04 04:10
Still happening.

**Comment by Dimentive** [comment] 2019-05-04 07:34
Is this ever going to be fixed? I can’t save pastes at all, so Hastebin is useless.

**Comment by butcha** [comment] 2019-06-05 15:49
Same issue here.

**Comment by Kabouik** [comment] 2019-06-06 08:01
It works again for me, but I am not sure when it was fixed. I am using the Budgie "HasteIt" applet.

**Comment by butcha** [comment] 2019-06-08 16:19
@Kabouik working here again now too 💪🤘

**Comment by jaylawl** [comment] 2019-06-18 22:43
happening again

**Comment by butcha** [comment] 2019-06-19 12:25
Yep, also happening here again now.

**Comment by SylveonBottle** [comment] 2019-06-25 08:53
Please use an alternative hastebin domain.

https://haste.aetheryx.xyz/

**Comment by Kabouik** [comment] 2019-06-25 09:13
Weird, I can confirm it still works for me with hastebin.com using the Budgie Haste applet.

**Comment by SylveonBottle** [comment] 2020-01-11 19:48
Having this issue still.. jeez, every other day with this.
