### ISSUE TITLE
Pages not loading with file extensions. Or bad server? hastebin.com

### ISSUE THREAD

**Issue by SilverCory** [seejohnrun/haste-server#103] opened 2016-02-06 14:55 UTC
It happens out of the blue on hastebin.com, something like this http://hastebin.com/itiwojicel.java

Orr, the server is crashed? http://i.imgur.com/hKhQz1U.png

**Comment by wheelerr** [comment] 2016-04-15 18:14
I have also experienced this problem. Its been in the code for some time now. Sometimes it works fine, sometimes it doesnt. I just remove the file extension but it kinda sucks having to do that.

**Comment by FichteFoll** [comment] 2016-04-15 22:57
I expect this to be a duplicate of https://github.com/seejohnrun/haste-server/issues/101, but I haven't seen your error symptoms. Do they match?

**Comment by SilverCory** [comment] 2016-04-15 23:07
There's no application error per se; there's just a blank document essentially. After removing the file extension the error fixes itself.

**Comment by seejohnrun** [comment] 2020-10-06 04:39
Thank you / I'm closing a lot of these duplicate issues to get the repo into a reasonable state

**Closed by seejohnrun** 2020-10-06 04:39 UTC
