### ISSUE TITLE
User higher resolution icons (or svgs) for hidpi screens

### ISSUE THREAD

**Issue by alexgleason** [seejohnrun/haste-server#147] opened 2017-01-30 18:26 UTC
Thanks for this wonderful tool!

On hidpi screens the favicon, logo, and UI icons appear blurry because the images are low resolution. This could be fixed by either increasing the resolution of those images or switching to SVGs. I recommend the latter.

Thanks!

**Comment by seejohnrun** [comment] 2017-01-30 19:36
cc / @bridawson !

**Comment by FussyLux** [comment] 2017-08-27 14:25
I think this is a Duplicate of #87

**Comment by seejohnrun** [comment] 2017-08-28 09:00
Duplicate of #87

**Closed by seejohnrun** 2017-08-28 09:00 UTC
