### ISSUE TITLE
Line numbers are not aligned with the code

### ISSUE THREAD

**Issue by ataalik** [seejohnrun/haste-server#74] opened 2014-10-04 09:09 UTC
I realised line numbers are not properly aligned on some pastes. An example : http://hastebin.com/uzajafasuh.js

**Comment by seejohnrun** [comment] 2020-10-07 03:39
I'm going to close this for now since I don't have access to the problematic code anymore. If anyone sees something like this in the wild please re-open this issue (or a new one) and we'll try to figure out where the problem is. There's a good chance things were resolved by recent upgrades as well

**Closed by seejohnrun** 2020-10-07 03:39 UTC
